# AST Configuration
# Created by Just1diax

cooldowns:
  chat:
    message: "&cPlease wait other %seconds% seconds before chatting again."
    enabled: true
    seconds: 5
  commands:
    message: "&cPlease wait other %seconds% seconds before using commands again."
    enabled: true
    seconds: 5